[package]
name = "riscv-emu"
version = "0.1.0"
authors = ["Lukas Wagner <lwagner94@posteo.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "^1.2.1"
lazy_static = "^1.3.0"
gdb-remote-protocol = { path = "rust-gdb-remote-protocol" }