name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt install libsdl2-dev
    - uses: actions/checkout@v2
    - name: Build
      run: | 
        rustc --version
        cargo build
    - name: Run tests
      run: cargo test
